name: 🐛 버그 리포트
description: 버그를 신고해주세요
title: "[Bug] "
labels: ["bug", "type/bug", "status/triaged"]
assignees:
  - project-maintainer

body:
  - type: markdown
    attributes:
      value: |
        버그를 신고해 주셔서 감사합니다! 자세한 정보를 제공해 주시면 더 빠르게 해결할 수 있습니다.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 버그 설명
      description: 발생한 버그에 대해 명확하고 간결하게 설명해주세요.
      placeholder: 어떤 문제가 발생했나요?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 재현 방법
      description: 버그를 재현할 수 있는 단계를 설명해주세요.
      placeholder: |
        1. '...' 로 이동
        2. '...' 클릭
        3. '...' 까지 스크롤
        4. 오류 확인
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 예상된 동작
      description: 어떤 결과를 기대했나요?
      placeholder: 예상된 동작을 설명해주세요
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 실제 동작
      description: 실제로 어떤 일이 일어났나요?
      placeholder: 실제 발생한 동작을 설명해주세요
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🏗️ 관련 컴포넌트
      description: 어떤 부분에서 문제가 발생했나요?
      options:
        - Backend/API
        - Frontend/UI
        - Database
        - Authentication
        - File Upload/Download
        - Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 심각도
      description: 이 버그의 심각도는 어느 정도인가요?
      options:
        - Critical (시스템 사용 불가)
        - High (주요 기능 영향)
        - Medium (일부 기능 영향)
        - Low (미미한 영향)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 환경 정보
      description: 어떤 환경에서 문제가 발생했나요?
      placeholder: |
        - OS: [예: macOS 13.0, Windows 11, Ubuntu 20.04]
        - Browser: [예: Chrome 118, Firefox 119, Safari 16]
        - Python Version: [예: 3.11.0]
        - 기타: [관련 정보]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 로그/에러 메시지
      description: 관련 로그나 에러 메시지가 있다면 붙여넣어 주세요.
      placeholder: 에러 메시지나 로그를 여기에 붙여넣어 주세요
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 스크린샷
      description: 문제를 보여주는 스크린샷이 있다면 추가해주세요.
      placeholder: 이미지를 드래그 앤 드롭하거나 붙여넣기로 추가할 수 있습니다.

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 추가 정보
      description: 이 버그와 관련된 추가 정보가 있나요?
      placeholder: 다른 관련 정보나 컨텍스트를 제공해주세요

  - type: checkboxes
    id: terms
    attributes:
      label: 체크리스트
      description: 다음 항목들을 확인해주세요
      options:
        - label: 기존 이슈를 검색했고 중복되지 않음을 확인했습니다
          required: true
        - label: 문제를 재현할 수 있습니다
          required: true
        - label: 가능한 한 자세한 정보를 제공했습니다
          required: true
